# Generated by Django 5.2.6 on 2025-10-03 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='予定タイトル')),
                ('start_time', models.DateTimeField(verbose_name='開始日時')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evnets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
